name: Laravel CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: |
        composer update --quiet --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        composer install --quiet --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Remove .env from FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: psc-dev.digitalnoticeboard.biz
        username: pscdevftp@psc-dev.digitalnoticeboard.biz
        password: "Slp;WQlqM~ja"
        serverPort: 21
        localDir: ./  # Path to your local directory to deploy
        remoteDir: /  # Remote directory to deploy to
        exclude: |
          vendor/**,
          .env,  # Exclude .env file
        delete: true  # Delete remote files not present in local directory

    - name: Create a copy of .env.staging
      run: cp .env.staging .env.staging_copy.php

    - name: Rename connection_staging_copy.php to .env
      run: mv .env.staging_copy.php .env

    - name: FTP Deploy to Staging
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: psc-dev.digitalnoticeboard.biz
        username: pscdevftp@psc-dev.digitalnoticeboard.biz
        password: "Slp;WQlqM~ja"
        serverPort: 21
        localDir: ./  # Path to your local directory to deploy (adjust as needed)
        remoteDir: /  # Remote directory to deploy to (adjust as needed)
        exclude: |
          vendor/**,
          node_modules/**,
          .git/**,
          .env,
          *.log,
          cache/**

    - name: Run php artisan storage:link
      run: php artisan storage:link
